### ISSUE TITLE
Region mapping the wrong region

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3011] opened 2018-06-25 23:56 UTC
When region mapping LGA region names we are not comparing the entire region name including the disaggregation part, we appear to be only using the name part. As a result when there are two LGA's with the same name we incorrectly map it. E.g. the LGA's `Murray (S)` which is in WA, and `Murray (A)` which is in NSW:

https://nationalmap.gov.au/renewables/#share=s-scpr4cGAm5VqSJ81

When region mapping names we need to use the full name string including the disaggregation part.

**Comment by meh9** [comment] 2018-06-26 01:32
The quickest way to work around this is to switch to using LGA codes instead of names.

**Comment by axman6** [comment] 2018-07-06 02:21
We just ran into this again - from the ABS docs on LGAs:

> Where the same Local Government Area name appears in different States or Territories, the State or Territory abbreviation appears in parenthesis after the name. Local Government Area names are therefore unique. 

http://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.003~July%202016~Main%20Features~Local%20Government%20Areas%20(LGA)~7

**Comment by AnaBelgun** [comment] 2018-07-09 01:37
Look at options; disambiguate; add another column; have 2 columns: name and LGA code 

- @meh9 advise to use codes
-  @steve9164 fix disambiguation with "State" - check if broken

**Comment by meh9** [comment] 2018-07-15 23:05
This has now been fixed.

**Comment by AnaBelgun** [comment] 2018-08-08 05:34
@AnaBelgun to let them know about the csv-geo-au template for LGAs

**Comment by AnaBelgun** [comment] 2018-11-08 21:54
Some more user feedback: 
- polygons from one state are showing up in another state. This occurs again because of the use of a national LGA layer to attach CSV files to. There are quite a few LGAs will the same name in different states. In the case below, a WA Broiler Litter Production polygon is returning biomass residues in the Murray LGA on the NSW/VIC border. There is a Murray LGA in both states

![csv issue regions2](https://user-images.githubusercontent.com/18452161/48229716-02eb3480-e3fd-11e8-98d5-410d5a63905a.png)

**Comment by stevage** [comment] 2018-11-12 05:53
>When region mapping LGA region names we are not comparing the entire region name including the disaggregation part, we appear to be only using the name part.

Yeah, this is basically by design. (My design). My thinking at the time was that attempting to use the suffix (such as "(S)" etc) only reduces the ambiguity, it doesn't solve it, which seemed to be a marginal gain. 

In other words: if you don't want ambiguity, either use LGA name plus state, or use LGA code. LGA_name is always prone to ambiguity.

To support this case would immediately raise questions like "Why didn't 'Shire of Murray' get matched against 'Murray (S)' instead of 'Murray (A)'?" IMHO.

**Comment by stevage** [comment] 2018-11-13 05:11
Yeah, it's a weird one. For some cases, the ambiguity just won't cause any problems at all, and that will just annoy the users. For others, not warning could be a big problem. I'm not sure how to resolve that.

**Comment by stevage** [comment] 2018-11-19 06:18
Oh, you mean warn that a region was actually ambiguous. Hmm. It potentially makes matching slower if you have to check for ambiguity. But I'd have to dive back into the code to really remember how that works - it's quite complex.

**Comment by AnaBelgun** [comment] 2018-11-26 00:10
@stevage 

- [ ] to Apply this fix to other maps: https://github.com/TerriaJS/TerriaMap/pull/275
including NatMap and InvestorMap
- [ ] Apply it to TerriaJS itself, so it will then propagate automatically to other maps when https://github.com/TerriaJS/TerriaMap/pull/277 goes through.

**Comment by stevage** [comment] 2018-12-18 05:39
For the first point, see https://github.com/TerriaJS/nationalmap/pull/823 and https://github.com/TerriaJS/InvestorMap/commit/c0ab26d0ef529a47fc5c115ffb0cf39deb7fc8c6 

For the second, see https://github.com/TerriaJS/TerriaMap/pull/284 and https://github.com/TerriaJS/terriajs/pull/3178

**Comment by AnaBelgun** [comment] 2019-02-03 23:48
connected to #3198

**Comment by stevage** [comment] 2019-02-03 23:48
Todo:

* [x] https://github.com/TerriaJS/terriajs/issues/3198
* [x] https://github.com/TerriaJS/nationalmap/pull/823#discussion_r250047509

**Comment by AnaBelgun** [comment] 2019-02-18 00:55
to test a WA sample file works now in Terria

**Comment by AnaBelgun** [comment] 2019-02-19 04:22
@meh9 ok, so the problem persists for the WA broiler data by LGA; the current dataset https://catalogue.data.wa.gov.au/dataset/broiler-litter-production/resource/f9b5d927-72d5-41cc-808f-0a99a44e1bac has the values by LGA_NAME_YEAR. What do they need to do? Change the column to LGA_Name_State or LGA_Code (as per ABS codes)?

![image](https://user-images.githubusercontent.com/18452161/52990041-5f2d0e00-345a-11e9-92cf-a51fa1efd4e5.png)

**Comment by AnaBelgun** [comment] 2019-02-19 05:11
ok, re-checked and it looks like it's working now (tested in pre-prod https://preprod.nationalmap.gov.au/renewables/) 

![image](https://user-images.githubusercontent.com/18452161/52991467-eaa99d80-3460-11e9-80f8-805d21b3a04a.png)

will close this now

**Closed as completed by AnaBelgun** 2019-02-19 05:11 UTC
Labels: T-Bug, P-AREMI, C-CSV/Region Mapping, Medium priority
