### ISSUE TITLE
Neither crosshair nor highlighting are shown for selected vector polygons and polylins

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2733] opened 2017-11-08 01:07 UTC
When you have a pure polygon layer such as a GeoJSON file, when you click on a feature and the feature info pops up, the crosshairs location marker quickly fades away and disappears, leaving you with no way to see where you actually clicked. Maybe not so bad since the user will have a reasonable idea of where they clicked, but if you share a feature info using a share URL, then when the user loads the share URL there is no indication which feature the feature info refers to.

E.g. using the following share URL there is no way to know which feature was clicked:

http://terria-cube.terria.io/#share=s-ot3NlpxfNZ5HzkFza7W57D6ZHee

**Comment by a-stacey** [comment] 2018-01-02 03:13
Does this PR help this issue at all?
https://github.com/TerriaJS/terriajs/pull/2722

In theory you should be able to turn the location marker on through the FeatureInfo to see the location (this needs to be done before the share URL is created), although this is not the cleanest UX experience).

---

Failing that, what should the user experience look like here, do we always want the crosshair to be left behind? do we want the crosshair only to remain if feature info is displayed? Is any of this changed if the above PR is merged? .... My feeling if the above PR is insufficient is that the cross hair remains until we know that we have no feature info at that location, this could potentially mean that the cross hair persists for a while as we may have to wait for the response from the feature info to complete before we know that it is ok to remove the cross hair (the alternative of it disappearing and then reappearing once the feature info is returned seems nasty).

**Comment by kring** [comment] 2018-02-08 00:36
Based on @meh9's link above, I think this is a straight-up bug.  When you click on one of the GeoJSON features, the target icon should appear and the feature should highlight. It looks like that isn't working, whether there are also raster layers active or not. I'm pretty sure this used to work and is a regression.

**Comment by kring** [comment] 2018-02-19 04:15
Consider #1421 in addressing this.

**Closed as completed** 2019-03-08 00:50 UTC
Labels: T-Bug, P-AREMI, P-TerriaCube, Bug Bash
