### ISSUE TITLE
Pop up timeseries controls immediately when enabling a CZML timeseries layer

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#545] opened 2015-02-18 02:14 UTC
When you turn on a CZML timeseries layer, it's necessary to click the layer name to focus on it before the timeseries controls popup. This is confusing to users since they don't know what layers are timeseries, so they don't know that they need to click on them. This effectively makes turning on a layer a two action process: first enable the layer, then click it again to see if it is a timeseries.

It would be better to pop up the timeseries controls immediately the layer is enabled instead.

**Comment by kring** [comment] 2015-02-18 02:25
This is a duplicate of #426.

**Closed as completed by kring** 2015-02-18 02:26 UTC
