### ISSUE TITLE
Mapserver accessed by URL parameters

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1029] opened 2015-11-04 00:25 UTC
I have no idea how common this is or if we want to support it, but it seems we can't handle a URL like this:

```
http://www.ntv.nntt.gov.au/IntraMaps/WMS_Server/bin/mapserv.exe?map=c:\IntraMaps\NNTT\WMS\NativeTitle.map& 
```

[GetCapabilities works](http://www.ntv.nntt.gov.au/IntraMaps/WMS_Server/bin/mapserv.exe?map=c:IntraMapsNNTTWMSNativeTitle.map&service=wms&request=GetCapabilities), but Terria doesn't seem to be able to handle this kind of URL with parameters required to access the server.

**Comment by kring** [comment] 2016-10-16 11:55
We can handle this by setting `"map": "c:\IntraMaps\NNTT\WMS\NativeTitle.map"` in the catalog items' `parameters` in the init file.

The trouble with making it work via Add Data is that it's hard to distinguish good URL parameters from bad ones.  Clearly if the user includes `request=GetCapabilities` in the URL, we shouldn't include that in `GetMap` requests.  Similarly, if we included a user-provided `bbox` parameter, everything would be broken.  So we'd need some kind of whitelist or blacklist of user-provided URL parameters.  Given that removing all parameters works pretty well in most cases, and we can create an init file in other cases, I'm going to close this.

**Closed as completed by kring** 2016-10-16 11:55 UTC
Labels: T-Enhancement, C-Catalogue, Z-Small

**Comment by rsignell-usgs** [comment] 2018-02-23 21:58
According to the [Mapserver documentation](http://mapserver.org/ogc/wms_server.html#changing-the-online-resource-url), the `map=` should not be considered a vendor-specific parameter since it is part of the Online Resource URL.   

So I think the Mapserver folks are arguing that: 

http://spatial.mtri.org/mapserver?map=%2Fvar%2Fwww%2Fmapfiles%2Fstampsands.map

is a valid WMS endpoint, and that clients should be able to issue successful `getCapabilities` requests like this:

http://spatial.mtri.org/mapserver?map=%2Fvar%2Fwww%2Fmapfiles%2Fstampsands.map&service=WMS&version=1.1.1&request=getCapabilities

and successful `getMap` requests like this:

http://spatial.mtri.org/mapserver?&map=%2Fvar%2Fwww%2Fmapfiles%2Fstampsands.map&SERVICE=WMS&VERSION=1.1.1&service=WMS&request=GetMap&layers=2009_substrate&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=256&height=256&srs=EPSG%3A4326&bbox=-88.1982421875,47.191578934752954,-88.19549560546875,47.19344533938292

This doesn't work  because TerriaJS is assuming that `?` is the split character for the endpoint, right?

**Comment by rsignell-usgs** [comment] 2018-02-23 22:26
I thought [specifying the `map` parameter in a catalog](https://github.com/USGS-CMG/terriajs-dive/blob/master/examples/stamp_sands.json) might work, but [this URL fails](https://gamone.whoi.edu/terriajs/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/stamp_sands.json) because the `describeLayer` request is not including the `map` parameter, which is not that surprising:
https://gamone.whoi.edu/terriajs/proxy/_1d/http://spatial.mtri.org/mapserver?service=WMS&version=1.1.1&sld_version=1.1.0&request=DescribeLayer&layers=2016_substrate

@kring, any ideas of a workaround?

**Comment by kring** [comment] 2018-02-26 23:37
@rsignell-usgs the `DescribeLayer` service is optional and not implemented by many WMS servers, so I don't think that's the problem.  More likely, the problem is the call to `GetCapabilities` is failing.  Unfortunately, TerriaJS currently does not automatically include the `parameters` in the GetCapabilities call. But you can specify `getCapabilitiesUrl` in the init file to force it to use a particular URL. So the workaround is, put `"getCapabilitiesUrl": "http://spatial.mtri.org/mapserver?map=%2Fvar%2Fwww%2Fmapfiles%2Fstampsands.map&service=WMS&version=1.1.1&request=getCapabilities"` in the init file, and also add `map` to the `parameters` part of the init file.
