### ISSUE TITLE
Hiding an imagery layer before it's fully rendered throws error

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1965] opened 2016-08-18 01:58 UTC
Well, I think that's what's going on.
1. On my local Parlmap build, I drag-drop all 7 files from https://github.com/TerriaJS/parlmap/files/412714/csvs.zip
2. _Go To Map_
3. Without waiting, start clicking the boxes to hide layers.

```
An error occurred while rendering.  Rendering has stopped.
undefined
DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (http://localhost:3005/build/TerriaMap.js:571:19)
    at Texture.throwOnDestroyed (http://localhost:3005/build/TerriaMap.js:45911:19)
    at ComputeCommand.postExecute (http://localhost:3005/build/TerriaMap.js:70193:33)
    at ComputeEngine.execute (http://localhost:3005/build/TerriaMap.js:254670:28)
    at ComputeCommand.execute (http://localhost:3005/build/TerriaMap.js:70587:23)
    at executeComputeCommands (http://localhost:3005/build/TerriaMap.js:250748:28)
    at executeCommandsInViewport (http://localhost:3005/build/TerriaMap.js:250924:13)
    at updateAndExecuteCommands (http://localhost:3005/build/TerriaMap.js:250818:17)
    at render (http://localhost:3005/build/TerriaMap.js:251154:9)
    at Scene.render (http://localhost:3005/build/TerriaMap.js:251192:13)
```

If you do wait, then the error doesn't occur.

**Comment by stevage** [comment] 2016-08-25 23:47
Looks like @steve9164 just saw this on NorthernAustralia map, on non-CSV layers.

**Comment by AlexGilleran** [comment] 2016-09-15 01:20
I can't reproduce this - I'm not sure if I'm too slow or my machine's too fast? :/

**Comment by kring** [comment] 2018-02-12 01:07
I can't reproduce this either, closing.

**Closed as completed by kring** 2018-02-12 01:07 UTC
Labels: T-Bug
