### ISSUE TITLE
Share URL splitter comparing two different times of same layer - layer copy missing time controls

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6824] opened 2023-07-19 00:00 UTC
Using this fresh Share URL to compare two times from the same layer using the splitter: https://nationalmap.gov.au/#share=s-vurwfi7gP5EgpmsySTG6QBzqBa6

Note how the `copy` layer is missing the time controls:

<img width="686" alt="Screenshot 2023-07-19 at 09 57 49" src="https://github.com/TerriaJS/terriajs/assets/5283003/61338d8f-341f-4c44-a5c3-fb0468600568">

Where did the time controls go?

**Comment by na9da** [comment] 2023-07-25 08:41
I think this is a duplicate of https://github.com/TerriaJS/terriajs/issues/6677

**Closed as completed** 2023-08-04 03:07 UTC
Labels: T-Bug
