### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by TonyHerrington** [TerriaJS/terriajs#3010] opened 2018-06-25 21:18 UTC
I have been trying to solve this problem for the better part of 2 days nows and could use some helpful feedback please.
I am running windows 10 on a surface pro 4 with node 8.11.3, react 16.4.1 and npm 6.1.0 installed. 

I have done a completed uninstall, cashe clear and removed all traces of js and reinstalled, twice, with no change in error status.

When running "npm install I recieve the following errors.

C:\Users\Tony\Local Sites\terriajs>npm install

> terriajs-cesium@1.41.2 postinstall C:\Users\Tony\Local Sites\terriajs\node_modules\terriajs-cesium
> bash -c "if [ ! -d "./wwwroot/build" ]; then gulp terria-prepare-cesium; fi"

'bash' is not recognized as an internal or external command,
operable program or batch file.
npm WARN html-to-react@1.2.12 requires a peer of react@^15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@0.53.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@0.53.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terriajs-cesium@1.41.2 postinstall: `bash -c "if [ ! -d "./wwwroot/build" ]; then gulp terria-prepare-cesium; fi"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terriajs-cesium@1.41.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tony\AppData\Roaming\npm-cache\_logs\2018-06-25T21_05_25_179Z-debug.log

**Comment by kring** [comment] 2018-06-25 23:53
Sorry you're having trouble @TonyHerrington. It looks like the problem is that bash isn't available on your system, and that's not surprising because I realize now we forgot to mention it in the prerequisites. The easiest way to get bash on Windows is to install Git for Windows: https://gitforwindows.org/. After you install it, use a Git Bash command prompt to follow the instructions in the Getting Started guide. Let me know how you go and I'll update the docs.

**Comment by TonyHerrington** [comment] 2018-06-26 00:33
I resolved the problem by running "npm install -g" then rerunning "npm install" in the local dir.
I have git installed and do have bash installed as well, thats why I was so confused.

**Comment by kring** [comment] 2018-06-26 00:56
Good to hear you found a solution, though I can't entirely explain why it worked. If you have Git Bash installed but yet you're seeing `'bash' is not recognized as an internal or external command,
operable program or batch file.`, my next guess is that bash isn't in your path? If you open a normal Windows command prompt, and type `bash`, does it drop you into bash or do you get an error? Did you run `npm install` from the Git Bash command prompt originally?

**Comment by kring** [comment] 2018-06-26 10:34
Closing this since you've been able to resolve the problem.

**Closed as completed by kring** 2018-06-26 10:34 UTC
