### ISSUE TITLE
ArcGisTiledMapServerCatalogItem

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#6161] opened 2022-02-23 04:19 UTC
Some ArcGIS MapServer endpoints actually serve WMTS-like https://developers.arcgis.com/rest/services-reference/enterprise/tile-map.htm . Although some of these work with ArcGisMapServerCatalogItem, we could implement dedicated support for these services, leading to better performance for these layers.

See forhttps://github.com/TerriaJS/terriajs/pull/6160#issuecomment-1048403548 for more info.

**Comment by rowanwins** [comment] 2022-02-23 05:44
So I think part of the reason this confused me was that CesiumJS actually handles this with it's `ArcGisMapServerImageryProvider`, namely the `usePreCachedTilesIfAvailable` property, which Terria is leveraging.
https://github.com/TerriaJS/terriajs/blob/main/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts#L475-L486

It's just a bit obscure, and needs a fairly detailed understanding of how Esri MapServers & Cesium & Terria work. So maybe there is a better way by implementing a `ArcGisTiledMapServerCatalogItem`?

**Comment by rowanwins** [comment] 2022-02-23 21:40
Maybe the other distinguishing thing is that you potentially have a different set of traits? Of the [`ArcGisMapServerCatalogItemTraits`](https://github.com/TerriaJS/terriajs/blob/main/lib/Traits/TraitsClasses/ArcGisMapServerCatalogItemTraits.ts) only the `tokenUrl` is relevant to tiled services, the rest like `parameters`, or `layers` are irrelevant.

**Comment by nf-s** [comment] 2022-11-10 04:36
Dupe of https://github.com/TerriaJS/terriajs/issues/5500

**Closed as completed by nf-s** 2022-11-10 04:36 UTC
