### ISSUE TITLE
Search for address or placename should indicate search result

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#296] opened 2014-08-08 14:19 UTC
User request (from a local council): Currently when you search for a placename, it just zooms in to the location but it isn't totally obvious where the successful search hit is.  It would be good to highlight this. Assuming we don't have access to the actual text on the basemap, we could just put a marker showing where the search hit is.

**Comment by hilarycinis** [comment] 2015-03-03 19:58
Are we thinking a simple place marker icon? http://www.google.com/intl/en_us/mapfiles/ms/icons/blue-dot.png
![blue-dot](https://cloud.githubusercontent.com/assets/6046521/6471009/d7a8d368-c23b-11e4-9f86-4799b1887083.png)

**Comment by stevage** [comment] 2015-04-29 07:39
I have noticed this same issue. One issue with dropping a pin (based on past experience with Google Maps) is the pin sometimes "hangs around" too long. I don't know when is the right time to remove it.  Better than current situation, anyway.

**Comment by kring** [comment] 2016-06-20 06:25
This is the oldest open issue in TerriaJS, and it's just been assigned to the next release!  Exciting!

**Comment by stevage** [comment] 2016-06-21 05:26
Also just pointing out that this part:

> and highlighting of polygons too

Was implemented ages ago in #1381. (Duplicate of #922)

**Comment by kring** [comment] 2016-06-29 04:26
Added in #1698

**Closed as completed by kring** 2016-06-29 04:26 UTC
Labels: T-Enhancement, A-Design and/or UX, C-Leaflet/Cesium
