### ISSUE TITLE
Version 8: WMS groups will request GetCapabilities twice

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4588] opened 2020-07-29 06:45 UTC
WMS groups will request GetCapabilities twice:
- Once when the group is loaded
- Again when a WMS item is loaded

Add a way to duplicate capabilities across group/items.

This is related to #4549

**Comment by rowanwins** [comment] 2020-09-25 04:13
Duplicate of #4740

**Closed as completed by rowanwins** 2020-09-25 04:13 UTC
Labels: Version 8
