### ISSUE TITLE
Comparison of data for multiple locations/areas

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2840] opened 2018-02-26 05:51 UTC
From user feedback:

Nice to have some demographics about aus. But I am unable to select more than one location to download ie select multiple/all LGA's for a single dataset as for example it would be useful to be able to compare many LGAs for a particular entity

Share URL: http://nationalmap.gov.au/#share=s-sTZwN9C6b27BJE70hQH1zdVeB1t

**Comment by kring** [comment] 2018-02-26 23:42
This is a duplicate of #1158.

**Closed as completed by kring** 2018-02-26 23:42 UTC
