### ISSUE TITLE
Once SDMX-JSON item fails to load for combination in 2D, mapping can fail

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2427] opened 2017-03-15 23:04 UTC
When in 2D mode, if SDMX-JSON item fails to load for a combination, all subsequent region-mapping can fail until you choose 3D.

**Comment by kring** [comment] 2018-02-08 06:30
Closing this because @RacingTadpole says in #2737 that he doesn't know how to reproduce this anymore.

**Closed as completed by kring** 2018-02-08 06:30 UTC
Labels: T-Bug, C-CSV/Region Mapping
