### ISSUE TITLE
Disable timeseries on CSV/DataTable dataset

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#932] opened 2015-09-23 22:48 UTC
We have built CSV services where one of the fields is named `Most Recent Output Time`. Because it has the word `time` at the end Terria will automatically turn that CSV into a timeseries layer and turn on the timeseries controls etc. In this case that isn't appropriate.

In other cases we might have several time columns for timeseries control, in which case we might need to specify which one (or several, which are turned on and off as you switch field in the legend?) can be used for the timeseries.

We might also want to define start and stop columns for specifying intervals.

It is probably appropriate to do automatic detection of all time columns when we just drag a CSV in, but to have these extra controls when used with init files.

In the init file maybe there should be something like:

```
"timeFields": "Time Col 1, Some other time col, And another"
```

Or when we don't want any timeseries:

```
"timeFields": ""
```

And when completely left out do the automagic timeseries.

I'm not entirely sure what to do in the start/stop interval case, maybe some magic `:` use? Not sure if that might restrict use of colons in column names too much:

```
"timeFields": "Start Col1:End Col 1, Start 2:End 2"
```

**Comment by stevage** [comment] 2016-02-25 00:49
Duplicate of #1070.

**Closed as completed by stevage** 2016-02-25 00:49 UTC
