### ISSUE TITLE
objectArrayTrait ordering across strata

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4675] opened 2020-08-26 05:13 UTC
The order of items in an `objectArrayTrait` change as values change across different strata.
For example, an `objectArrayTrait` is provided by a `LoadableStratum`, and then a value is added to the user stratum.

**Comment by soyarsauce** [comment] 2020-08-26 05:16
duplicate of https://github.com/TerriaJS/terriajs/issues/4559

**Closed as completed by soyarsauce** 2020-08-26 05:16 UTC
Labels: T-Bug, Version 8
