### ISSUE TITLE
Poor KML/KMZ support

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1358] opened 2016-03-01 04:43 UTC
I just looked at lots of KML files I have lying around, and almost none of them display much in 2D mode. [Example](https://www.dropbox.com/s/9a4dco7qk6tococ/OverlandTrack.kml?dl=0):

2D:
![screenshot 2016-03-01 15 38 50](https://cloud.githubusercontent.com/assets/678344/13417865/c02ab372-dfc3-11e5-8da7-2f4adcbf99de.png)

3D:
![screenshot 2016-03-01 15 38 59](https://cloud.githubusercontent.com/assets/678344/13417867/c356d2ba-dfc3-11e5-8360-c905068ec2fb.png)

The log shows issues like:
- `Uncaught TypeError: Cannot read property 'color' of undefined`
- `KML - Unsupported feature node: html`
- `KML - Unsupported feature: ScreenOverlay`

Some errors showed up in Cesium mode:
- `Uncaught DeveloperError: cartesian is required.`
- `Error loading image for billboard: [object Event]`

Perhaps at least we should warn the user that our KML support isn't as good as they expect, and they may not see much.

**Comment by kring** [comment] 2016-03-01 05:30
The KML support (which turns a KML file into Cesium entities) is shared between Cesium and Leaflet, but the Leaflet visualizer, which turns Cesium entities into things on the Leaflet map, is pretty rough.  There's a separate issue for the things it doesn't support (#564) and probably plenty of bugs as well.

**Comment by kring** [comment] 2018-02-19 05:31
Duplicate of #1887.

**Closed as completed by kring** 2018-02-19 05:31 UTC
Labels: T-Enhancement, C-Leaflet/Cesium, Z-Medium
