### ISSUE TITLE
Support styling GeoJSON files

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#811] opened 2015-07-06 00:42 UTC
Currently GeoJSONs are assigned random colours. Kevin says Cesium already supports [SimpleStyle](https://github.com/mapbox/simplestyle-spec) so we just need to expose that in init files.

**Comment by kring** [comment] 2015-07-06 01:22
The problem is that TerriaJS currently explicitly clobbers the styling information loaded by Cesium (from simplestyle).  It was written before Cesium added that feature.  We just need to change it to specify GeoJSON default styles instead of explicitly setting styles after load.  See the `loadGeoJson` function in `GeoJsonCatalogItem.js`.

**Comment by hilarycinis** [comment] 2015-07-09 22:27
I've added a task to our trello board that associates to this - to create a colour legend reference to suggest  what kinds of features could be which colour.

**Comment by stevage** [comment] 2015-07-15 03:21
This is now implemented: https://github.com/TerriaJS/terriajs/commit/9c2486b5c257c8cb5e6555659ad50d4b382efce6

@hilarycinis, I'm not sure I quite understand - are you talking about having the legend show which randomly chosen colour is given to each GeoJSON file when there isn't an explicit color given? Or even when there is? Probably should be a different issue?

**Comment by hilarycinis** [comment] 2015-07-15 05:00
@stevage nope, proposing a style guide reference for folks creating a data set and unsure what colours are a good idea. eg if I'm a data custodian working on creating a vegetation data set, then the style guide may recommend using shades of green. Also by examining regularly used data sets we might be able to better advise colour for discoverability when sets are used together.

**Comment by stevage** [comment] 2015-07-15 06:54
Oh, interesting. It'd need to consider what our basemap is/will be, and
obviously the actual data format used (GeoJSON is still pretty uncommon in
government circles compared to shapefile or WMS...)

**Comment by kring** [comment] 2015-07-27 01:48
@stevage this is done right?  Can we close it?

@hilarycinis it sounds like what's on the Trello board is a bit different from what's described in this issue.  We could keep this issue open and and change the title to match what's in the board, or write a new issue, or just dissociate the Trello item from GitHub, or whatever works for you.

**Comment by hilarycinis** [comment] 2015-07-27 02:11
yeah no worries, I've closed it in our trello as it was a placeholder to promote thought rather than a to-do

**Closed as completed** 2015-07-27 12:17 UTC
