### ISSUE TITLE
tableStyle min/maxDisplayValue reset ignored when returning to dataVariable view

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#798] opened 2015-07-01 01:58 UTC
When viewing a dataset with a `tableStyle` `dataVariable` that has a `minDisplayValue` or `maxDisplayValue`, when going to the Legend tab and selecting a different column to view data for, and then switching back to the original specified dataVariable any `minDisplayValue` or `maxDisplayValue` set is ignored, and the legend min/max is then autosized to the min and max of the data.

For example:
1. open the `test.json` init file in NM
2. enable the `Test Data` -> `Files` -> `Auto Incidents (CSV) layer`
3. switch to `Now Viewing`/Legend tab
4. note that the default column is set to `incident_duration` and the legend has specific min of 0 and max of 1500
5. switch to `day_of_week` and then back to `incident_duration`
6. note that the legend is now autosized and the specified `minDisplayValue` and `maxDisplayValue` have been ignored

**Comment by kgrochow** [comment] 2015-07-01 02:13
This is by design.  The reason is that the tableStyle is not per variable, so switching variables means that it has probably no meaning for the new variable, so it is discarded and default styling applies from then on out.  If you don't want the user to switch variables then you can use disableUserChanges: true in the table style.

**Comment by meh9** [comment] 2015-09-03 05:33
I agree that a `tableStyle` in most cases has no meaning for different variables. However, when switching back to the variable it was originally specified for, I think it makes sense to again apply the table style - I don't think the user expects the action of switching between different variables will have a different result when switching back to the original variable.

**Comment by RacingTadpole** [comment] 2016-02-25 01:05
Fixed via https://github.com/TerriaJS/terriajs/pull/1302

**Closed as completed by RacingTadpole** 2016-02-25 01:05 UTC
