### ISSUE TITLE
WMS 'Groundwater Contours' not uploading

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2274] opened 2016-12-13 23:03 UTC
What do I need to do to get Terria working with MapServer WMS? I have the same layer working with WFS off of MapServer so it shouldn't be an error connecting to the MapServer. (WMS is enabled, works fine as WMS in OpenLayers).

I've tried variants of:

// this version, replacing "layers" with "typeNames" and "wms" with "wfs" works
{
  "name": "Groundwater Contours",
  "type": "wms",
  "url": "http://website.org/cgi-bin/mapserv", 
  "layers": "contours", 
  "parameters": {
    "map": "/var/path/to/mapfile.map"
  }
}, 
// also tried with "layers" pulled out of URL but map still in
{
  "name": "Groundwater Contours",
  "type": "wms",
  "url": "http://website.org/cgi-bin/mapserv?map=/var/path/to/mapfile.map&layers=contours"
} 

With either I get: "Missing data. The WMS dataset 'Groundwater Contours' did not return any data."

The XML returned from getCapabilties looks fine too. The layer shows up as:

<Layer queryable="0" opaque="0" cascaded="0">
  <Name>contours</Name>
  <Title>Groundwater Contours</Title>
  <CRS>EPSG:4326</CRS>
  <EX_GeographicBoundingBox>
    <westBoundLongitude>-122.441</westBoundLongitude>
    <eastBoundLongitude>-118.838</eastBoundLongitude>
    <southBoundLatitude>35.0309</southBoundLatitude>
    <northBoundLatitude>40.5896</northBoundLatitude>
  </EX_GeographicBoundingBox>
  <BoundingBox CRS="EPSG:4326" minx="35.0309" miny="-122.441" maxx="40.5896" maxy="-118.838"/>
</Layer>

Likewise I have a MapCache TMS (same server) which takes request in the form of:  http://website.org/mapcache/tms/1.0.0/layer@grid/[z]/[x]/[y].png

Get capabilities URL is: http://website.org/mapcache/tms/1.0.0/?service=tms&request=getCapabilities
Which returns XML in format of:

<TileMapService version="1.0.0">
  <TileMaps>
    <TileMap title="The Layer" srs="EPSG:3857" profile="none" href="http://website.org/mapcache/tms/1.0.0/layername@gridname"/>

Not sure from documentation how to set that up in the catalog json. It says web tile-map-service is supported, but not even sure what the value for "type" should be. "wtms" and "tms" both fail as unrecognized.

Thanks.

**Comment by AnaBelgun** [comment] 2016-12-13 23:04
So the MapServer WMS issue is because it doesn't take any parameters and cleans the URL. So instead of doing:
 
http://website.org/cgi-bin/mapserv?map=/var/path/to/mapfile.map&service=WMS&version=1.3.0&request=GetCapabilities
 
..it's always cleaning the URL down to the base for and doing:
 
http://website.org/cgi-bin/mapserv?service=WMS&version=1.3.0&request=GetCapabilities


As WebMapServiceCatalogItem doesn't take a "parameters" variable, whereas WebFeatureServiceCatalogItem appends all "parameters" into the URL request. This of course returns nothing as MapServer needs a map on which to take the request.
 
So solution here is some mod_rewrite or similar solution so a certain URL wms request always rewrites to the cgi-bin path with the "map" get parameter automatically added. We have control over our MapServer here and most services will likely implement similar to clean up the URL, but might be something worth adjusting in the future.
 
For 2nd issue had to do a bit of digging. Just since I couldn't find it in the documentation, going to list out all the catalog member types I found being used: abs-itt, abs-itt-dataset-list, resulting-pending, async-result, bing-maps, ckan, ckan-resource, composite, csv, csw, cesium-terrain, czml, esri-group, esri-featureServer, esri-featureServer-group, esri-mapServer, esri-mapServer-group, geojson ,gps, group, kml, kmz, ogr, open-street-map, sdmx-json, socrata, sos, url-template, wfs, wfs-features-group, wfs-getCapabilities, wms, wms-getCapabilities, wmts, wmts-getCapabilities, wps-getCapabilities, wpgs-result, wps.
 
Doesn't seem to be TMS support but I just used url-template, which uses Cesium's UrlTemplateImageryProvider that has relevant info on parameters. I also think MapCache supports WMTS so that is an option but I didn't te

**Comment by kring** [comment] 2016-12-13 23:25
This issue was created from this forum post:
https://groups.google.com/d/topic/terriajs/84fQnd1XvAA/discussion

While it points to the need for more documentation, it's not a bug, so I'm closing this issue.  I've responded to the original post.

**Closed as completed by kring** 2016-12-13 23:25 UTC
