### ISSUE TITLE
Enable indexing by search engines 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2846] opened 2018-02-28 04:30 UTC
This issues came up several times. 
Here is a copy from user feedback: 
Great interface, very impressive. Biggest shortcoming is the inaccessibility of the content to everyday web users because map layers are not exposed to web search engines. E.g. Google "Annual climatology of daily exposure - Direct Normal Exposure" - doesn't show. Same issue that was highlighted in a review of the ASDD back around 2000: people who knew about it loved it, but 90% of target users were pissed off they didn't know about it.

**Comment by jondoig** [comment] 2018-02-28 04:35
sounds like something I'd say :wink:

**Comment by kring** [comment] 2018-02-28 04:51
Duplicate of #1757.

**Closed as completed by kring** 2018-02-28 04:51 UTC

**Comment by AnaBelgun** [comment] 2018-02-28 04:53
I knew it was a similar one but couldn't find it :)
