### ISSUE TITLE
Create support for clustering large point datasets 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2821] opened 2018-02-15 00:14 UTC
The user has issues with uploading large point data files on the maps; in this example, JASON file had 84,000 sites (95MB). 
https://github.com/TerriaJS/neii-viewer/issues/100

From @kring : 
85k points isn’t necessarily prohibitive for Cesium, but probably is for Leaflet.  And in any case it’s likely to be on the slow side, and might need to go through a different path to be efficient in Cesium (e.g. don’t use 85k entity objects).

The usual approach for point datasets of that size is clustering, which Cesium and Leaflet both support in different ways but TerriaJS doesn’t yet support at all. To avoid the need to download/parse a 95MB JSON file, you can potentially use pre-clustered vector tiles (MapBox or Cesium), but neither one is supported in TerriaJS at the moment. Or rasterize them, of course.

**Comment by rowanwins** [comment] 2020-01-06 04:31
Duplicate of #2821

**Closed as completed by rowanwins** 2020-01-06 04:31 UTC
Labels: T-Enhancement, C-Leaflet/Cesium
