### ISSUE TITLE
Getting the cool tiles.rdnt.io service working

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#3662] opened 2019-08-23 12:51 UTC
I wanted to test out the cool [tiles.rdnt.io service by radiantearth](https://github.com/radiantearth/tiles.rdnt.io) which turns any Cloud-Optimized Geotiff into a  tile service.   The URLs works in ipyleaflet, but don't seem to work in Terria, for example: 

https://tiles.rdnt.io/tiles/{z}/{x}/{y}?url=https://opendata.digitalglobe.com/cyclone-kenneth/pre-event/2017-07-31/105001000B1C1400/3323122.tif

Here's a share URL from Terria:
https://nationalmap.gov.au/#share=s-spwqEfLfPuvW1UdKwTJ6fmA946h

**Comment by rowanwins** [comment] 2019-08-26 05:24
Hi @rsignell-usgs 

That's a super cool service, it's been on our to-do list to look at some sort of COG rendering.

I suspect the problem is that Terria prunes off additional params, notably the url of the COG in this case.

I'll have a ponder on a good way to support this service... it may be that we stand up our own instance and create a new Model which allows tweaking some of the params (eg the used bands etc).

Thanks for bringing it to our attention.

**Comment by rsignell-usgs** [comment] 2019-09-22 18:34
Here's an example just showing that the tiles.rdnt.io tile service for COGS works in leaflet: 
http://tiles.rdnt.io/preview?url=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fplanet-disaster-data%2Fhurricane-harvey%2FSkySat_Freeport_s03_20170831T162740Z3.tif#15/28.968623060961647/-95.35427562765338

We are starting to generate COGs here at USGS and we would really like to display them in TerriaJS.

**Comment by rsignell-usgs** [comment] 2020-09-30 13:51
@nf-s, I see you self-assigned yourself.   Any progress or roadblocks? 

In case it's useful, here's an example request:
https://tiles.rdnt.io/tiles/18/41791/98635?url=https%3A%2F%2Fprod-is-usgs-sb-prod-publish.s3.amazonaws.com%2F5e7d36c1e4b01d5092751e09%2FWhiskeytown_2019-06-03_DSM_25cm_hll.tif

this is one of the requests from: 
https://www.cogeo.org/map/#/url/https%3A%2F%2Fprod-is-usgs-sb-prod-publish.s3.amazonaws.com%2F5e7d36c1e4b01d5092751e09%2FWhiskeytown_2019-06-03_DSM_25cm_hll.tif/center/-122.6017,40.6341/zoom/16

**Comment by rsignell-usgs** [comment] 2020-10-01 03:19
To support this, could we add a "append" option to the [`open-street-map` catalog item type](https://docs.terria.io/guide/connecting-to-data/catalog-type-details/open-street-map/)?

I'm thinking something like:
```
          "type": "open-street-map",
          "url": "https://tiles.rdnt.io/tiles/",
          "append": "?url=https%3A%2F%2Fprod-is-usgs-sb-prod-publish.s3.amazonaws.com%2F5e7d36c1e4b01d5092751e09%2FWhiskeytown_2019-06-03_DSM_25cm_hll.tif"
```
Would that work?

**Comment by nf-s** [comment] 2020-10-01 13:34
Hi @rsignell-usgs , sorry I haven't had a chance to look into it yet - I was hoping to have a crack a few months ago but it didn't happen unfortunately.
I am very interested in this and client-side (cloud-optimised) geotiff support, I am hoping to get a little bit of time to do this in the next few months, I will keep you posted!

**Comment by rsignell-usgs** [comment] 2020-10-02 17:28
@kring provided a [solution on Google Groups](https://groups.google.com/g/terriajs/c/6ofzMC328jI/m/e_H8vlfACAAJ
) using the `url-template` catalog item instead of `open-street-map`, @urbanows set this up and it works great:
https://maps.usgs.gov/map/#https://raw.githubusercontent.com/urbanows/TerriaMapConfigs/master/cog.json
![2020-10-02_12-03-09](https://user-images.githubusercontent.com/1872600/94952052-4d736f80-04b3-11eb-878e-da349afb229d.jpg)

**Comment by rsignell-usgs** [comment] 2020-10-02 17:30
@meh9 and @nf-s, should I leave this open or go ahead and close?

**Comment by meh9** [comment] 2020-10-06 07:44
> I suspect the problem is that Terria prunes off additional params, notably the url of the COG in this case.

Great that it has solved the problem. Another way of doing it would be to add the `parameters` property like we have for WMS? https://docs.terria.io/guide/connecting-to-data/catalog-type-details/wms-getCapabilities/

**Comment by meh9** [comment] 2020-10-06 07:45
@rsignell-usgs yes, I think we can close it now, thanks!

**Closed as completed by meh9** 2020-10-06 07:45 UTC

**Comment by rowanwins** [comment] 2020-10-06 23:41
For completeness the catalog item looked like 
````
{
   "name": "COG S3 Test",
    "type": "url-template",
    "zoomOnEnable": true,
    "isEnabled": true,
    "isShown": true,
    "rectangle": [
        "-122.6333437",
        "40.591483",
        "-122.5152576",
        "40.6623342"
    ],
    "url": "https://api.cogeo.xyz/cog/tiles/{z}/{x}/{y}?url=https%3A%2F%2Fprod-is-usgs-sb-prod-publish.s3.amazonaws.com%2F5e7d36c1e4b01d5092751e09%2FWhiskeytown_2019-06-03_DSM_25cm_hll.tif"
}
````
