### ISSUE TITLE
Share URL does not maintain layer order

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1315] opened 2016-02-19 04:59 UTC
We've been testing the new share URL code, and it seems that the order layers are drawn on the map are not preserved - layers that were on top (either because of there order they were turned on or which have been reordered by hand) can move to the bottom of the stack of layers in the legends area and on the map.

**Comment by kring** [comment] 2018-02-19 06:09
Duplicate of #2824 (well technically the other way around, but there's more detail there and the newer issue is more likely to be noticed).

**Closed as completed by kring** 2018-02-19 06:09 UTC
Labels: T-Bug, P-AREMI, C-Catalogue, C-Sharing
