### ISSUE TITLE
Add opacity slider for CZML and CSV(-lat-lon) layers

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1285] opened 2016-02-09 04:45 UTC
Currently CZML files are rendered above all other layers without any method to change the opacity. This makes viewing the data along with other layers pretty difficult. CSVs using lat/lon columns also suffer the same problem.

**Comment by kring** [comment] 2018-02-19 06:13
Duplicate of #1442.

**Closed as completed by kring** 2018-02-19 06:13 UTC
Labels: T-Enhancement, P-AREMI, C-UI, C-CSV/Region Mapping
