### ISSUE TITLE
Choose a better default column for csvs

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2045] opened 2016-09-13 03:55 UTC
`CsvCatalogItem` currently selects the first enum or scalar column.  

I think using the first scalar column, if it exists, would be much better, and using an enum only if none exists.

Eg. when you open data.gov.au's National Innovation spreadsheet by SA3, the first displayed column is `sa3_name_2011`, which results in a bad first impression of the data - it colors the first 20 SA3s in alphabetical order and the rest grey.

![image](https://cloud.githubusercontent.com/assets/1757858/18461042/96c895fe-79b9-11e6-8370-5f7dda20f602.png)

**Comment by stevage** [comment] 2016-09-13 04:22
Duplicate of #1322 ?

**Closed as completed by stevage** 2016-09-13 04:22 UTC

**Comment by RacingTadpole** [comment] 2016-09-13 04:45
Thanks! I did look for an existing issue, but didn't find that one... it can also apply to lat/lon csvs btw.
