### ISSUE TITLE
Location filters are not automatically applied to split workbench layers

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3419] opened 2019-05-22 06:14 UTC
### Problem
Currently, when a user splits a layer that has a location filter applied to it, the resulting duplicate layer appears in the workbench without a matching filter and the following prompt is shown on the map (indefinitely) 
![Screen Shot 2019-05-22 at 4 11 09 pm](https://user-images.githubusercontent.com/5292858/58151204-555eb500-7cac-11e9-9fa6-6cdac1681f10.png)

After splitting a layer that has a location filter applied to it, the duplicate workbench item displays a loading spinner that appears to displace the 'filter by location button (resolves after loading is complete)

![Screen Shot 2019-05-27 at 10 31 26 am](https://user-images.githubusercontent.com/5292858/58389207-ae8f6580-806b-11e9-8cf6-0fa2e7bf2997.png)

### Proposed solution
When a workbench layer has a location filter applied to it, that filter should automatically be applied to all duplicate layers created via the 'split' function. 

_Note: this behaviour will obviously not apply if the user splits a layer, activates split view, THEN applies a location filter via feature info (as that filter will only be applied to one side of the map). Complexity ensues._

**Comment by philipgrimmett** [comment] 2019-07-11 05:57
**Feedback via NationalMap**
> When splitting data after filtering by location, the copy doesn't preserve the filtering. This means I additionally have to filter the copy, which takes additional time. Ideally, the copy would preserve the filtering.

**Comment by AnaBelgun** [comment] 2019-07-18 23:55
duplicate of https://github.com/TerriaJS/terriajs/issues/3596
will close this one

**Closed as completed by AnaBelgun** 2019-07-18 23:55 UTC
