### ISSUE TITLE
The wrong or no timeline can appear when you enable/disable datasets

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2577] opened 2017-06-23 06:52 UTC
Try this with two different time-varying datasets, A (let's say it covers Time A) and B (Time B):

1. Add A. The timeline shows Time A. Good.
2. Then add B. The timeline shows Time B. Good. (You can repeat 1 & 2 over and over, and it keeps working.)
3. Then disable A: the timeline disappears. It should have been unaffected, as it showed Time B.
4. Re-enable A and the timeline shows Time A. Good.
5. Then disable A: the timeline disappears. It should have changed to Time B.

Here's something that's fine: If you did steps 1 & 2 and then:
3B. Disable B: the timeline goes back to Time A. Good.
4B. Re-enable B: back to Time B. Good.

Some logic somewhere is misfiring.

**Comment by kring** [comment] 2018-02-08 05:27
I can't reproduce this.  I tried using `Auto Incidents (CSV)` and `Chlorophyll-a concentration (monthly)` from `#test` in NationalMap.  The timeline behaves as expected with the procedure above and with similar things that I tried.  So I'm closing this on the assumption we've fixed it, but please re-open if you're still able to make it happen.

**Closed as completed by kring** 2018-02-08 05:27 UTC
