### ISSUE TITLE
CZML polygons appear and disappear when zooming

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#912] opened 2015-09-11 06:54 UTC
Attached are two CZML files where the one with transparent outlines will disappear at certain zoom levels, while the one with opaque outlines does not. On my system it happens when the scale is between 20-10km. Once the particular zoom level where it happens has been found, then it's possible to zoom in and out just at the limit and have the polygon show and then disappear again repeatedly.

There are two polygons, one in Canberra and one in Melbourne. Note that if either of the polygons is removed then the problem stop. In AREMI, if when the problem is happening you enable another CZML file with opaque outlines, the problem stops and the polygon then shows again.

I tried these on the CesiumJS Cesium Viewer demo, and there the problem does not occur, while on AREMI and the NationalMap it does. 

My system is a 13" retina Macbook Pro, 2013 model, running OSX Mavericks, with integrated Intel HD 5100 graphics. It also occurs on a 2012 15" Macbook Pro with Intel HD 4000 graphics. It does not happen when switching that one to the discrete NVIDIA graphics.

Happy to discuss more.

https://www.dropbox.com/s/4kqipv8xej125z0/opaque.czml?dl=0

https://www.dropbox.com/s/bvk4aa4d1tywzf8/transparent.czml?dl=0

**Comment by kring** [comment] 2016-10-05 01:14
@meh9 does this still happen on your system?  I guess I'm hoping since it didn't happen on the Cesium Viewer demo at the time, it's been fixed in Cesium and by now that fix has appeared in TerriaJS.  If not, is it perhaps caused by terrain being enabled in NationalMap (and maybe AREMI at the time?) but not in the Cesium Viewer?

**Comment by kring** [comment] 2018-02-22 00:48
I'm closing this, but you can re-open if you still see it @meh9 and it's causing problems for you.

**Closed as completed by kring** 2018-02-22 00:48 UTC
Labels: T-Bug, C-Leaflet/Cesium
