### ISSUE TITLE
WMTSCatalogGroup doesn't use canonical base URL

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1371] opened 2016-03-03 04:12 UTC
We have discussed using WMTS to access some layers that have to be fast but do not require feature info. However, for some reason none of the GA WMTS layers show any data on TerriaJS. The loading bar moves but nothing is shown.

Example service:

http://services.ga.gov.au/gis/rest/services/NationalMap_Colour_Topographic_Base_World_WM/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

**Comment by stevage** [comment] 2016-03-15 03:17
Is there a reason you're including the capabilities part? Using just this URL seems to work ok: http://services.ga.gov.au/gis/rest/services/NationalMap_Colour_Topographic_Base_World_WM/MapServer/WMTS

**Comment by stevage** [comment] 2016-03-15 03:29
Ok, looks like the issue is that the WMTS Item gets constructed just fine with the URL you gave, but then it also gets used as the tile base path, so you get a url constructed like this:

http://services.ga.gov.au/gis/rest/services/NationalMap_Colour_Topographic_Base_World_WM/MapServer/WMTS/1.0.0/WMTSCapabilities.xml?service=WMTS&version=1.0.0&request=GetTile&tilematrix=3&layer=NationalMap_Colour_Topographic_Base_World_WM&style=default&tilerow=4&tilecol=7&tilematrixset=urn%3Aogc%3Adef%3Awkss%3AOGC%3A1.0%3AGoogleMapsCompatible&format=image%2Fpng

Probably the WMTS Catalog Group should be looking at `<ows:Operation name="GetTile">` to get the base URL: `<ows:Get xlink:href="http://services.ga.gov.au/gis/rest/services/NationalMap_Colour_Topographic_Base_World_WM/MapServer/WMTS/tile/1.0.0/">`

In the mean time I'd suggest just using the shorter URL.

**Comment by kring** [comment] 2018-02-19 05:14
The `url` property in a WMTS catalog item needs to be the base URL of the WMTS service. So yeah, pointing it at an XML document won't work. The WMTS GetCapabilities does have a `ResourceURL`, so in theory we could start with the XML, extract the ResourceURL, and then use that for tile requests.  It all seems pretty roundabout, though, when you can just point at the proper service URL.

I don't think there's anything to fix here, so I'm closing this.

**Closed as completed by kring** 2018-02-19 05:14 UTC
Labels: P-AREMI, C-Catalogue
