### ISSUE TITLE
Lat / Long Info + Share

### ISSUE THREAD

**Issue by a-stacey** [TerriaJS/terriajs#2697] opened 2017-10-19 22:34 UTC
@meh9 and I were discussing this morning how to better handle sharing of a specific point.

- For every point that the user clicks the lat/long should be displayed in the feature information. This is both in the case where there is already feature information displayed at the point (in this case the lat long should appear at the bottom, and when there is not - just the lat/lon should appear) and where there is no other feature info (in this case it should be the only item displayed.
- The cross hair should remain visible. (Currently when there is no feature info the cross hair fades out immediately).

We also think that it would be nice to make this share more easily. (From the above implementation you should then be able to click on the share link and share the point with the point highlighted, but this may require more intuition then what could be expected from a casual user). We think that if the lat/lon were linked to the share button (lan/lon click is a synonym for the share button) so that when clicked on the lat lon the share panel opens up (originally I suggested that it was a link to the share link, but @meh9 pointed out that in order to do that a share link would need to be created each time, with would pollute the database).

(Note: Add crosshair to what is displayed in this image).
![no other info](https://user-images.githubusercontent.com/4453477/31797666-3a89e398-b57b-11e7-8417-2f9253e4adcf.png)

![where other info present](https://user-images.githubusercontent.com/4453477/31797295-48e6bcce-b579-11e7-8a23-09bdd7cfdb35.png)

**Comment by meh9** [comment] 2017-10-19 22:43
This is basically fairly similar to being able to click anywhere to place a pin, and share the location of the pin. It's much more about sharing/highlighting the location of something than the data available at the point.

**Comment by meh9** [comment] 2017-10-19 22:43
@philipgrimmett what do you think? :)

**Comment by meh9** [comment] 2017-10-21 00:00
In addition to the lat/lon we should also show elevation.

**Comment by philipgrimmett** [comment] 2017-10-23 01:30
@meh9 @a-stacey Re: lat/lon being included in feature info: yep, it's been on the wish list for a while! My bad for not creating an issue earlier.

As for sharing a point/feature location: might need to think this one over. Clicking on lat/lon in the feature info panel to launch Share feels a bit odd, but maybe we could clarify by including the share icon?

![screenshot 2017-10-23 12 29 35](https://user-images.githubusercontent.com/5292858/31868709-d94ad072-b7ed-11e7-88e4-69f6c64cb4a2.png)

**Comment by a-stacey** [comment] 2018-01-02 03:18
Just adding a screenshot of as implemented as I needed to do a build to double check something else anyway.

![image](https://user-images.githubusercontent.com/4453477/34473508-ba047b8e-efc7-11e7-91a3-cc4ade6d7ac1.png)

**Comment by kring** [comment] 2018-02-08 00:56
Is this a duplicate of #2706?

**Comment by a-stacey** [comment] 2018-02-08 01:25
So technically this is not a duplicate of #2706, but it is closely related (here we are really making the selected location available / there it is sharing search location), they are both addressed in the same PR https://github.com/TerriaJS/terriajs/pull/2722 (where I merge the to concepts into one with the location marker concept) which is ready for review and merge and would close both issues.

**Closed as completed** 2018-02-15 05:11 UTC
