### ISSUE TITLE
Download data for multiple point/area selection

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2854] opened 2018-03-01 04:02 UTC
User feedback:

Good day Sir/Madam,

What a great product!!!

I was trying to download data from multiple datapoint. Does the National Map supports multiple point/group selection data download?

Share URL: http://nationalmap.gov.au/#share=s-ueP4bSIamsPvfBm5mMXBL4Ku0Xk

**Comment by AnaBelgun** [comment] 2018-03-01 04:03
I think we might have covered this; currently not possible

**Comment by kring** [comment] 2018-03-01 04:24
Duplicate of #1306 and/or #1158.

**Closed as completed by kring** 2018-03-01 04:24 UTC
