### ISSUE TITLE
Google URL shortener often fails

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1590] opened 2016-06-03 06:26 UTC
The Google URL Shortener often fails to shorten things - I suspect that this is due to the length of the URL we are trying to shorten.

Try creating a shortened URL with a few layers enables, most likely the POST request will fail with a status of 400 and this response:

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Value",
    "locationType": "parameter",
    "location": "resource.longUrl"
   }
  ],
  "code": 400,
  "message": "Invalid Value"
 }
}
```

**Comment by meh9** [comment] 2016-06-03 07:10
bit.ly also says it's not a valid URL. 

People are suggesting online that 2047 chars is the max limit.

**Comment by stevage** [comment] 2016-06-06 06:08
This is a duplicate of #1342 isn't it?

**Closed as completed by stevage** 2016-06-06 06:08 UTC
Labels: P-AREMI, C-Sharing
