### ISSUE TITLE
Can't select all format types

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3552] opened 2019-06-28 00:17 UTC
When trying to add new data we now have so many formats supported that the drop down is very long. Unfortunately we can't scroll it, so if the list is longer than the screen you can't see or select things at the bottom:

<img width="574" alt="Screen Shot 2019-06-28 at 10 14 58" src="https://user-images.githubusercontent.com/5283003/60308808-e3098080-998d-11e9-863e-9d78c8311b6f.png">

**Comment by rowanwins** [comment] 2019-06-28 01:51
Duplicate of #3337
Resolved by #3380

**Closed as completed by rowanwins** 2019-06-28 01:51 UTC
Labels: T-Bug
