### ISSUE TITLE
`svg-sprite-loader` is broken on a version after 4.1.3

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#3339] opened 2019-04-29 01:48 UTC
might be related to webpack v4 (https://github.com/kisenka/svg-sprite-loader/issues/248), more info to come

**Comment by Borovensky** [comment] 2019-05-02 13:23
Yeah, also have the issue with it.
`"webpack": "^4.25.1"`
`"svg-sprite-loader": "^4.1.6"` 
seems to incomparable. Forced to lock svg-sprite-loader on 4.1.3 version to make it work.

**Comment by kring** [comment] 2019-05-03 01:44
@Borovensky this is caused by a bug in newer `svg-sprite-loader` where it resolves the location of webpack incorrectly using `require.main.resolve`. When running via a _global_ gulp, using `require.main.resolve` will try to resolve it from your global npm modules directory. If that directory has the wrong version of webpack, things break.

The solution is easy: use the local (installed in the TerriaMap directory) version of gulp by running it with `npm run gulp` or `./node_modules/.bin/gulp`.

**Comment by kring** [comment] 2019-05-07 00:17
Fixed in #3357 by pinning to v4.1.3 (for now). This has been shipped in TerriaJS v7.4.1.

**Closed as completed by kring** 2019-05-07 00:17 UTC
