### ISSUE TITLE
Labelling for vector and region-mapped datasets

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2869] opened 2018-03-02 04:15 UTC
User feedback:

It should be possible to apply data labels to the map rather than needing to click on a location to get information about the layer. For example, it would be much more convenient to be able to overlay statistical boundary or postcode labels on the map so that these are visible on the map.

**Comment by stevage** [comment] 2018-03-13 04:08
I think that's a duplicate of #2532. You might also consider whether to allow it for CSV datasets, and if so, how to express that in csv-geo-au.

**Comment by kring** [comment] 2018-03-13 04:26
You're right, it's a duplicate, thanks @stevage.

**Closed as completed by kring** 2018-03-13 04:26 UTC
Labels: T-Enhancement
