### ISSUE TITLE
v7 - v8 migration: documentation "getting started" 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5667] opened 2021-07-23 03:51 UTC
- [ ] Update documentation section: "get started: https://docs-v8.terria.io/guide/getting-started/
- [ ] note the link to branch name, should be changed from next to main

Shall we included examples of common errors like these: 
**Problem**
Build error when building TerriaMap: 
ERROR in /home/steve/Data61/Terria-PacificMap/node_modules/terriajs/lib/ReactViews/Tools/DiffTool/DiffTool.tsx
./node_modules/terriajs/lib/ReactViews/Tools/DiffTool/DiffTool.tsx
[tsl] ERROR in /home/steve/Data61/Terria-PacificMap/node_modules/terriajs/lib/ReactViews/Tools/DiffTool/DiffTool.tsx(244,5)
  	TS2322: Type '(AvailableStyle | undefined)[]' is not assignable to type 'AvailableStyle[]'.
  Type 'AvailableStyle | undefined' is not assignable to type 'AvailableStyle'.
	Type 'undefined' is not assignable to type 'AvailableStyle'.
**Solution**
Upgrade TerriaMap’s typescript version by syncing from terriajs. I.e. when using workspaces:
npx sync-dependencies --source terriajs --from packages/terriajs/package.json
And when developing against mobx without workspaces:
npx sync-dependencies --source terriajs

**Problem**
Yarn install throws error An unexpected error occurred: "expected workspace package to exist for \"pkg-dir\"" (or similar with a different package).
Sometimes yarn versions above yarn@1.19.0 will cause an error when running yarn install using workspaces. The Github issue describing it https://github.com/yarnpkg/yarn/issues/7807 has comments saying it’s caused by a workspace trying to install a different version of the same dependency.
**Workaround**
Easiest fix is to install dependencies using an older version of yarn:
npx yarn@1.19.0 install
It’s possible the problem could also be fixed in certain cases by syncing dependency versions for the same package, and ensuring that a workspace doesn’t install the same dependency but with a different version. Syncing dependencies could help:
gulp sync-terriajs-dependencies

**Comment by na9da** [comment] 2021-07-27 03:37
- [ ] The link to "Deploying" is broken, fix it
- [ ] "download a zip file" link also points to `next`. Change it to `main.zip` instead.
- [ ] Link to "Problems and solutions" from getting started page.
- [ ] Make sure terriajs is updated to have the latest version of cesium so that the default cesium token works and we do not get a black screen for the map.
- [ ] Document updating `cesiumIonAccessToken` if the map fails to load.
- [ ] Remove the entire section on prettier now that it is the default in v8
- [ ] Replace links to gitter & google groups with github discussions.
- [ ] Fix relative links to other pages. ~Currently this is broken because a `/` gets added to the end of the getting started URL.~ This can be fixed by linking to the `.md` pages instead.

**Comment by na9da** [comment] 2021-07-27 03:46
> Shall we included examples of common errors like these:

The listed problems appears to be too specific to be discussed in getting started. Ideally we should fix the problems so that they do not occur in the first place. If the problem is not easily fixable and is a common occurrence, then maybe we should document it in an FAQ. v7 docs has a [Problems and Solutions](https://docs.terria.io/guide/contributing/problems-and-solutions/) guide.

I'll walk through the steps in the guide and see if I get any of those problems.

**Comment by nf-s** [comment] 2021-07-28 10:57
Closed by https://github.com/TerriaJS/terriajs/pull/5682

**Closed as completed by nf-s** 2021-07-28 10:57 UTC
Labels: High priority
