### ISSUE TITLE
Don't use transparent as "no data" color (because Cesium-drawn empty circles are nearly unclickable)

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#799] opened 2015-07-01 03:25 UTC
When adding tabular data to Cesium containing points and some lines do not have a value for whatever column is currently being visualised, then these points are drawn "empty", i.e. no colour fill. Unfortunately this makes the point very hard to click since it appears you have to click the line of the circle in order to bring up the data for that point.

The `Test` entry in this CSV shows the issue once dragndropped onto NM:

```
Some data, Place, Lat, Lon, Data1, Data2
1, NICTA,-35.2817828,149.1248208, Some more data from the CSV, And some more
4, Parkwood Road Substation,-35.2195879,148.996752, Some more data from the CSV, And some more
5, Cotter Dam,-35.3202023,148.9398087, Some more data from the CSV, And some more
,Test,-35.29,149, Some more data from the CSV, And some more
```

**Comment by stevage** [comment] 2015-07-16 09:39
Closely related issue: points in GeoJSON files with marker icons are very hard to click on as well - you have to click on the very base of the signpost (not the sign itself).

**Comment by kring** [comment] 2015-07-18 13:00
The difficulty in clicking marker icons is caused by AnalyticalGraphicsInc/cesium#2894.

**Comment by meh9** [comment] 2016-01-28 23:28
This has been highlighted by GA testing of AREMI. It would be nice to have this fixed, as it is a problem we just live with at the moment.

The best way to test is to turn on `Electricity Inf.` -> `Generation` -> `Current Power Generation` -> `All` in AREMI and play around clicking inside and on the edge of the unfilled circles:

http://nationalmap.gov.au/renewables/#share=0fR0dV

**Comment by stevage** [comment] 2016-02-03 04:14
Ok, so let's reframe this issue as "Don't leave circles unfilled, even when there is no data". Then it becomes a lot simpler. At the least, we could use a very low opacity colour.

**Comment by meh9** [comment] 2016-02-03 10:44
I do like the look of having the circles empty, as that really says "no value" to me. If we can retain that look, or something like it using a a nearly transparent colour (or white?) would be great.

**Comment by RacingTadpole** [comment] 2016-02-07 22:40
FYI, #1250 added a `nullColor` option to `tableStyle`: "defaults to a dark blue. This colour is used to display null values (but it does not appear on the legend; we should add it). It is also used to colour points when no variable is selected."

**Comment by RacingTadpole** [comment] 2016-02-09 00:45
I believe this is fixed now by the addition of `nullColor`, `replaceWithNullValues` and `replaceWithZeroValues`.
At least the sample csv file you give above @meh9 works now, because by default missing numerical values are now shown as if zero (which makes the AREMI electricity data work nicely); you can change this to make them show as the nullColor (defaulting to black) by setting `replaceWithNullValues` and `replaceWithZeroValues`.

**Closed as completed by RacingTadpole** 2016-02-09 00:45 UTC
Labels: P-AREMI
