### ISSUE TITLE
URL sharing of timeseries layers is broken

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1592] opened 2016-06-03 07:30 UTC
Creating a share URL (shortened or unshortened) of a timeseries layer and following the link results in a broken Terria instance with no catalogue or timeseries (i.e. JS has hit an error somewhere).

To test, go to http://nationalmap.gov.au/#test -> Test Data -> Temporal -> Chlorophyll

**Comment by stevage** [comment] 2016-06-23 07:09
Reproduced: http://nationalmap.gov.au/#share=xcqTlO

**Comment by RacingTadpole** [comment] 2016-06-24 06:55
The good news is I can't reproduce this either in the current master (f07f6d7), or in the `newui` branch.
I hope this means it has magically been fixed.
For reference, in case it is still a problem, the error seems to be that when you open the shared link, `animationViewModel.refreshTimeline` refers to `this.timeline`, which is `undefined`.

**Comment by kring** [comment] 2016-07-12 01:58
No longer a problem, closing.

**Closed as completed by kring** 2016-07-12 01:58 UTC
Labels: T-Bug, C-Sharing
