### ISSUE TITLE
Mobx: iOS white screen

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4813] opened 2020-09-30 01:04 UTC
Repro:
On an iOS (tested with iOS 14) device
1. http://ci.terria.io/next/
2. observe loading modal
3. observe white screen after terria thinks it has started

**Comment by zoran995** [comment] 2021-04-07 09:04
Is this a duplicate of #4670

**Closed as completed** 2024-12-15 19:11 UTC
Labels: Bug Bash
