### ISSUE TITLE
[Epic] Update The Docs

### ISSUE THREAD

**Issue by staffordsmith83** [TerriaJS/terriajs#6439] opened 2022-07-19 09:13 UTC
Go through the docs and update/delete/flag.

Some of this will be related to migration from V7 to V8, but not all.

Try to approach the docs as though a community member was using them.

@steve9164 is currently working on Getting Started.

**Comment by AnaBelgun** [comment] 2023-01-10 01:42
duplicate of https://github.com/TerriaJS/terriajs/issues/5166

**Closed as completed by AnaBelgun** 2023-01-10 01:42 UTC
Labels: Epic
