### ISSUE TITLE
NM Search could search data in loaded WFS layers

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#566] opened 2015-03-02 06:26 UTC
When a WFS layer is enabled and loaded, it would be really cool if when you run a NM Search query it would also search through the data of the loaded WFS layers.

For example, if you add/enable the ASEIS Power Stations WFS layer from this URL:

http://www.ga.gov.au/gis/services/energy/ASEIS_Features/MapServer/WFSServer?service=WFS&version=1.1.0&request=GetFeature&typeName=energy_ASEIS_Features:Power_Stations&srsName=EPSG%3A4326&maxFeatures=10000&outputFormat=GML3

Then if you do a NM Search for Tumut, the search should bring up results for the Tumut power stations, and let you click the result to travel there.

**Comment by keithmoss** [comment] 2016-04-21 08:36
A big +1 for this from Western Australia via the ESRI REST API.

e.g. Find all features with wildcard LIKE `%Bay%` on the `name` field.

https://services.slip.wa.gov.au/public/rest/services/WAM_Public_Services/WAM_Public_Services/MapServer/0/query?where=name+LIKE+%27%25Bay%25%27&outFields=name%2Cwhen_lost&returnGeometry=true&outSR=4326&f=pjson

**Comment by kring** [comment] 2016-10-04 05:57
Closing as a duplicate of #1324.  Even though that issue was written later, it is more general.

**Closed as completed by kring** 2016-10-04 05:57 UTC
Labels: T-Enhancement, C-Catalogue, Z-Medium
