### ISSUE TITLE
Further organise documentation

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1476] opened 2016-04-28 06:04 UTC
Tasks:
* [x] We have documentation in both the tutorial (built by jsdoc) and Documentation folders. Let's move the tutorial into Documentation.
* [x] Let's add a link to the built jsdoc documentation (eg. http://nationalmap.gov.au/build/TerriaJS/doc/TableColumnStyle.html, or another hosted version of it).
* [ ] Currently the idea is that "customizing" requires javascript coding, and "catalog management" does not. Let's make that more explicit, or change that.
* [ ] Let's update the homepage of terria.io to point to the new documentation.

As a point of comparison, Django’s docs https://docs.djangoproject.com are often cited as being very good (at least by Djangonauts). They break the docs into: tutorials, topic guides, reference guides, and how-to guides. But there’s no equivalent to a non-coding developer.

**Comment by kring** [comment] 2018-02-19 02:25
I'm going to close this because two of the tasks have already been done, a third (update the homepage) is trivial and we don't need a reminder to do it (though possibly when this was written the docs weren't linked from the homepage), and the remaining task is quite general. I agree with the sentiment (our docs could be better) but I don't think the issue is doing much for us.

**Closed as completed by kring** 2018-02-19 02:25 UTC
Labels: T-Documentation
